// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package repository

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (provider_id, password, user_id)
VALUES ($1, $2, $3)
RETURNING id, provider_id, password, user_id
`

type CreateAccountParams struct {
	ProviderID string `json:"provider_id"`
	Password   string `json:"password"`
	UserID     string `json:"user_id"`
}

type CreateAccountRow struct {
	ID         string `json:"id"`
	ProviderID string `json:"provider_id"`
	Password   string `json:"password"`
	UserID     string `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ProviderID, arg.Password, arg.UserID)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Password,
		&i.UserID,
	)
	return i, err
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT id, provider_id, password, user_id
FROM accounts
WHERE id = $1
`

type FindAccountByIDRow struct {
	ID         string `json:"id"`
	ProviderID string `json:"provider_id"`
	Password   string `json:"password"`
	UserID     string `json:"user_id"`
}

func (q *Queries) FindAccountByID(ctx context.Context, id string) (FindAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i FindAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Password,
		&i.UserID,
	)
	return i, err
}

const findAccountByUserID = `-- name: FindAccountByUserID :one
SELECT id, provider_id, password, user_id
FROM accounts
WHERE user_id = $1
`

type FindAccountByUserIDRow struct {
	ID         string `json:"id"`
	ProviderID string `json:"provider_id"`
	Password   string `json:"password"`
	UserID     string `json:"user_id"`
}

func (q *Queries) FindAccountByUserID(ctx context.Context, userID string) (FindAccountByUserIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByUserID, userID)
	var i FindAccountByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Password,
		&i.UserID,
	)
	return i, err
}

const findAccountByUserIdAndProviderID = `-- name: FindAccountByUserIdAndProviderID :one
SELECT id, provider_id, password, user_id
FROM accounts
WHERE user_id = $1 AND provider_id = $2
`

type FindAccountByUserIdAndProviderIDParams struct {
	UserID     string `json:"user_id"`
	ProviderID string `json:"provider_id"`
}

type FindAccountByUserIdAndProviderIDRow struct {
	ID         string `json:"id"`
	ProviderID string `json:"provider_id"`
	Password   string `json:"password"`
	UserID     string `json:"user_id"`
}

func (q *Queries) FindAccountByUserIdAndProviderID(ctx context.Context, arg FindAccountByUserIdAndProviderIDParams) (FindAccountByUserIdAndProviderIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByUserIdAndProviderID, arg.UserID, arg.ProviderID)
	var i FindAccountByUserIdAndProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Password,
		&i.UserID,
	)
	return i, err
}
