// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EnumRole string

const (
	EnumRoleAdmin   EnumRole = "admin"
	EnumRoleManager EnumRole = "manager"
	EnumRoleUser    EnumRole = "user"
)

func (e *EnumRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumRole(s)
	case string:
		*e = EnumRole(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumRole: %T", src)
	}
	return nil
}

type NullEnumRole struct {
	EnumRole EnumRole `json:"enum_role"`
	Valid    bool     `json:"valid"` // Valid is true if EnumRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumRole) Scan(value interface{}) error {
	if value == nil {
		ns.EnumRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumRole), nil
}

type Account struct {
	ID         string             `json:"id"`
	ProviderID string             `json:"provider_id"`
	Password   string             `json:"password"`
	UserID     string             `json:"user_id"`
	UserRole   EnumRole           `json:"user_role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string             `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
