// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, expires_at, user_id, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, expires_at, user_id
`

type CreateSessionParams struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    string             `json:"user_id"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

type CreateSessionRow struct {
	ID        string             `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    string             `json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Token,
		arg.ExpiresAt,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const deleteSessionByUserId = `-- name: DeleteSessionByUserId :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionByUserId(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSessionByUserId, userID)
	return err
}

const findSessionByToken = `-- name: FindSessionByToken :one
SELECT id, token, expires_at, user_id
FROM sessions
WHERE token = $1
`

type FindSessionByTokenRow struct {
	ID        string             `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    string             `json:"user_id"`
}

func (q *Queries) FindSessionByToken(ctx context.Context, token string) (FindSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, findSessionByToken, token)
	var i FindSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const findSessionByUserId = `-- name: FindSessionByUserId :one
SELECT id, token, expires_at, user_id
FROM sessions
WHERE user_id = $1
`

type FindSessionByUserIdRow struct {
	ID        string             `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    string             `json:"user_id"`
}

func (q *Queries) FindSessionByUserId(ctx context.Context, userID string) (FindSessionByUserIdRow, error) {
	row := q.db.QueryRow(ctx, findSessionByUserId, userID)
	var i FindSessionByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const updateSessionByUserId = `-- name: UpdateSessionByUserId :one
UPDATE sessions SET token = $1, expires_at = $2, ip_address = $3, user_agent = $4
WHERE user_id = $5
RETURNING id, token, expires_at, user_id
`

type UpdateSessionByUserIdParams struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	UserID    string             `json:"user_id"`
}

type UpdateSessionByUserIdRow struct {
	ID        string             `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    string             `json:"user_id"`
}

func (q *Queries) UpdateSessionByUserId(ctx context.Context, arg UpdateSessionByUserIdParams) (UpdateSessionByUserIdRow, error) {
	row := q.db.QueryRow(ctx, updateSessionByUserId,
		arg.Token,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
	)
	var i UpdateSessionByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}
